### ISSUE TITLE
Error when running. Some dependencies out of date

### ISSUE THREAD

**Issue by terryupton** [TrigenSoftware/gulp-srcset#2]
Seems a few dependancies are out of date and get the following error when running:
```
[17:31:38] Starting 'srcset'...
[17:31:38] 'srcset' errored after 6.11 ms
[17:31:38] Error: Cannot find module '@babel/runtime/core-js/promise'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/terryupton/Dropbox/Amasci/Websites/Martin Williams V2/martinwilliamsart.co.uk/node_modules/gulp-srcset/lib/index.js:5:32)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
```

**Comment by dangreen** [comment]
@terryupton try new release https://github.com/TrigenSoftware/gulp-srcset/releases/tag/v2.0.1
