### ISSUE TITLE
 TypeError: srcset is not a function

### ISSUE THREAD

**Issue by yudyananda** [TrigenSoftware/gulp-srcset#26]
Hi there

I;m using 
CLI version: 2.2.0
Local version: 4.0.2

I can make the gulp task images woking 

tested with this gulpfile.js 
~~~
const gulp = require('gulp');
const srcset = require('gulp-srcset');

gulp.task('images', () =>
    gulp.src('src/*.{jpg,png,gif}')
        .pipe(srcset([{
            match: '(min-width: 3000px)',
            width: [1, 1920, 1280, 720, 560, 320],
            format: ['jpg', 'webp']
        }]))
        .pipe(gulp.dest('dist'))
);
~~~

the result was 
~~~
gulp images
[15:12:51] Using gulpfile E:\YUDY\WEB PROJECT\CLIENTS\Peci Iming\LIVE\Site\noimageproc\gulpfile.js
[15:12:51] Starting 'images'...
[15:12:51] 'images' errored after 45 ms
[15:12:51] TypeError: srcset is not a function
    at gulp.task (E:\YUDY\WEB PROJECT\CLIENTS\Peci Iming\LIVE\Site\noimageproc\gulpfile.js:6:15)
    at taskWrapper (E:\YUDY\WEB PROJECT\CLIENTS\Peci Iming\LIVE\Site\noimageproc\node_modules\undertaker\lib\set-task.js:13:15)
    at bound (domain.js:375:14)
    at runBound (domain.js:388:12)
    at asyncRunner (E:\YUDY\WEB PROJECT\CLIENTS\Peci Iming\LIVE\Site\noimageproc\node_modules\async-done\index.js:55:18)
    at process._tickCallback (internal/process/next_tick.js:112:11)
~~~

any idea?

**Comment by dangreen** [comment]
@yudyananda 

```js
const srcset = require('gulp-srcset').default;
```

**Comment by yudyananda** [comment]
another test

~~~
const gulp = require('gulp');
const srcset = require('gulp-srcset').default;

gulp.task('images', () =>
    gulp.src('src/*.{jpg,png,gif}')
        .pipe(srcset([{
            match: '(min-width: 200px)',
            width: [1, 1920, 1280, 720, 560, 320],
            format: ['jpg', 'webp']
        }]))
        .pipe(gulp.dest('dist'))
);
~~~

result 

~~~
gulp images
[15:36:00] Using gulpfile E:\YUDY\WEB PROJECT\CLIENTS\Peci Iming\LIVE\Site\noimageproc\gulpfile.js
[15:36:00] Starting 'images'...
[15:36:00] 'images' errored after 167 ms
[15:36:00] TypeError: Object is not async iterable
    at _asyncIterator (E:\YUDY\WEB PROJECT\CLIENTS\Peci Iming\LIVE\Site\noimageproc\node_modules\@babel\runtime\helpers\asyncIterator.js:16:9)
    at Promise.all.rules.map (E:\YUDY\WEB PROJECT\CLIENTS\Peci Iming\LIVE\Site\noimageproc\node_modules\gulp-srcset\lib\index.js:54:34)
    at <anonymous>
~~~

not sure if it has a relation with my issue but when i try to check task list `gulp --task` the resul was

~~~
gulp --task
[15:36:29] Using gulpfile E:\YUDY\WEB PROJECT\CLIENTS\Peci Iming\LIVE\Site\noimageproc\gulpfile.js
[15:36:29] Task never defined: default
[15:36:29] To list available tasks, try running: gulp --tasks
~~~

**Comment by dangreen** [comment]
@yudyananda https://github.com/TrigenSoftware/gulp-srcset/issues/9#issuecomment-500190307
which node version are you using?

**Comment by yudyananda** [comment]
i'm using v9.7.1

which version is recommended?

**Comment by yudyananda** [comment]
solved after update latest node version.

thanks bro
