### ISSUE TITLE
TypeError: Object is not async iterable

### ISSUE THREAD

**Issue by excme** [TrigenSoftware/gulp-srcset#9]
`gulp.task('respImages', () =>
    gulp.src(paths.webroot + 'images/*.{jpg,jpeg,png}')
        .pipe(srcset([{
            width:  [1920, 1280, 720, 560, 320],
            format: ['webp']
        }]))
        .pipe(gulp.dest(paths.webroot + 'images-dist'))
);`

Log:
`> respImages: STARTED
> respImages: Using gulpfile c:\Users\COMP03\source\repos\gulpfile.js
> respImages: Starting 'respImages'...
> respImages: 'respImages' errored after 30 ms
> respImages: FAILED
> respImages: TypeError: Object is not async iterable
> respImages: at _asyncIterator (c:\Users\COMP03\source\repos\node_modules\@babel\runtime\helpers\asyncIterator.js:16:9)
> respImages: at c:\Users\COMP03\source\repos\node_modules\gulp-srcset\lib\index.js:61:38
> respImages: at Generator.next (<anonymous>)
> respImages: at asyncGeneratorStep (c:\Users\COMP03\source\repos\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
> respImages: at _next (c:\Users\COMP03\source\repos\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
> respImages: at <anonymous>`

**Comment by dangreen** [comment]
@excme Hi. You can try it with more newer node version.
